### ISSUE TITLE
Initial issue tracking:

### ISSUE THREAD

**Issue by PipGrylls** [paramm-team/data_processing#15]
1. Requirements updates - 

- [x] Add Nox
- [x] Add jupyter/ipykernal
- [x] Remove MPL
- [x] Unify setup and requirements

From running MSM_Faraday_…Importer.ipynb:

2. File path in notebooks - 

- [x] Data download cell switch to ./
- [x] Examples cells

3. Pandas Dtypewarning

Running basic_example:

4. ~~Module Resolution~~

Overall:

5. ~~Mixture of plotly and mpl~~
6. ~~Use of OS path, should be updated to pathlib (also relevent to 2)~~

**Comment by PipGrylls** [comment]
7. Add a logger

**Comment by PipGrylls** [comment]
This is all done closing
